name: Hello World!

on:
  push:
    branches:
      - master
    # pull_request:
    # branches: [master]
    # types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    env: 
      MONGODB_URI: ${{ secrets.MONGODB_URI }} 
      TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }} 
      PORT: ${{ secrets.PORT }} 
      SECRET: ${{ secrets.SECRET }} 
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install
        run: npm install && cd client && npm install
      - name: lint
        run: npm run lint:all
      - name: build
        run: npm run build:client
      - name: test backend
        run: npm run test
      - name: test frontend
        run: npm run test:client
      - name: test e2e
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm run start:test
          wait-on: http://localhost:3001
      - name: pushing code to heroku
        uses: akhileshns/heroku-deploy@v3.8.9
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "part11-bloglist"
          heroku_email: "julius.lubys@gmail.com"
          procfile: "web: npm start"