name: Hello World!

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    env: 
      MONGODB_URI: ${{ secrets.MONGODB_URI }} 
      TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }} 
      PORT: ${{ secrets.PORT }} 
      SECRET: ${{ secrets.SECRET }} 
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install
        run: npm install && cd client && npm install
      - name: lint
        run: npm run lint:all
      - name: build
        run: npm run build:client
      - name: test backend
        run: npm run test
      - name: test frontend
        run: npm run test:client
      - name: test e2e
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm run start:test
          wait-on: http://localhost:3001
      - name: pushing code to heroku
        uses: akhileshns/heroku-deploy@v3.8.9
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "part11-bloglist"
          heroku_email: "julius.lubys@gmail.com"
          healthcheck: "https://pokedexbyjulius.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true
        env:
          HD_MONGO_URI: ${{ secrets.MONGODB_URI }} 
          HD_SECRET: ${{secrets.SECRET}}
          HD_SKIP_PREFLIGHT_CHECK: true
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.33.0
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
      # - uses: 8398a7/action-slack@v3
      #   with:
      #     status: custom
      #     fields: commit,author,took
      #     custom_payload: |
      #       {
      #         username: 'github_action',
      #         attachments: [{
      #           color: 'good',
      #           text: `A new version deployed to https://part11-bloglist.herokuapp.com/ (${process.env.AS_COMMIT}) by ${process.env.AS_AUTHOR} build in ${process.env.AS_TOOK}`,
      #         }]
      #       }
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      #   if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') && success() }}
      # - uses: 8398a7/action-slack@v3
      #   with:
      #     status: ${{ job.status }}
      #     fields: all
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      #   if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') && failure() }}